#include "gdk_error.h"
#include <classes/engine.hpp>

using namespace godot;

void GDKXErrorOptions::_bind_methods() {
    BIND_BITFIELD_FLAG(GDKXErrorOptions::None);
    BIND_BITFIELD_FLAG(GDKXErrorOptions::OutputDebugStringOnError);
    BIND_BITFIELD_FLAG(GDKXErrorOptions::DebugBreakOnError);
    BIND_BITFIELD_FLAG(GDKXErrorOptions::FailFastOnError);
}

void GDKError::_bind_methods() {
    BIND_ENUM_CONSTANT(GDK_OK);
    BIND_ENUM_CONSTANT(GDK_FALSE);

    BIND_ENUM_CONSTANT(GDK_DSTORAGE_BEGIN);
    BIND_ENUM_CONSTANT(GDK_DSTORAGE_END);

    BIND_ENUM_CONSTANT(GDK_GAMERUNTIME_NOT_INITIALIZED);
    BIND_ENUM_CONSTANT(GDK_GAMERUNTIME_DLL_NOT_FOUND);
    BIND_ENUM_CONSTANT(GDK_GAMERUNTIME_VERSION_MISMATCH);
    BIND_ENUM_CONSTANT(GDK_GAMERUNRIME_WINDOW_NOT_FOREGROUND);
    BIND_ENUM_CONSTANT(GDK_GAMERUNTIME_SUSPENDED);
    BIND_ENUM_CONSTANT(GDK_GAMERUNTIME_UNINITIALIZE_ACTIVEOBJECTS);
    BIND_ENUM_CONSTANT(GDK_GAMERUNTIME_MULTIPLAYER_NOT_CONFIGURED);
    BIND_ENUM_CONSTANT(GDK_GAMERUNTIME_MISSING_DEPENDENCY);
    BIND_ENUM_CONSTANT(GDK_GAMERUNTIME_SUSPENDED_ACTIVEOBJECTS);
    BIND_ENUM_CONSTANT(GDK_GAMERUNTIME_OPTIONS_MISMATCH);
    BIND_ENUM_CONSTANT(GDK_GAMERUNTIME_OPTIONS_NOT_SUPPORTED);
    BIND_ENUM_CONSTANT(GDK_GAMERUNTIME_GAMECONFIG_BAD_FORMAT);
    BIND_ENUM_CONSTANT(GDK_GAMERUNTIME_INVALID_HANDLE);
    BIND_ENUM_CONSTANT(GDK_GAMERUNTIME_SERVICE_NOT_AVAILABLE);

    BIND_ENUM_CONSTANT(GDK_GAMEUSER_NO_AUTH_USER);
    BIND_ENUM_CONSTANT(GDK_GAMEUSER_USER_NOT_IN_SANDBOX);
    BIND_ENUM_CONSTANT(GDK_GAMEUSER_MAX_USERS_ADDED);
    BIND_ENUM_CONSTANT(GDK_GAMEUSER_SIGNED_OUT);
    BIND_ENUM_CONSTANT(GDK_GAMEUSER_RESOLVE_USER_ISSUE_REQUIRED);
    BIND_ENUM_CONSTANT(GDK_GAMEUSER_DEFERRAL_NOT_AVAILABLE);
    BIND_ENUM_CONSTANT(GDK_GAMEUSER_USER_NOT_FOUND);
    BIND_ENUM_CONSTANT(GDK_GAMEUSER_NO_TOKEN_REQUIRED);
    BIND_ENUM_CONSTANT(GDK_GAMEUSER_NO_DEFAULT_USER);
    BIND_ENUM_CONSTANT(GDK_GAMEUSER_FAILED_TO_RESOLVE);
    BIND_ENUM_CONSTANT(GDK_GAMEUSER_NO_TITLE_ID);
    BIND_ENUM_CONSTANT(GDK_GAMEUSER_UNKNOWN_GAME_IDENTITY);
    BIND_ENUM_CONSTANT(GDK_GAMEUSER_NO_PACKAGE_IDENTITY);
    BIND_ENUM_CONSTANT(GDK_GAMEUSER_FAILED_TO_GET_TOKEN);
    BIND_ENUM_CONSTANT(GDK_GAMEUSER_INVALID_APP_CONFIGURATION);
    BIND_ENUM_CONSTANT(GDK_GAMEUSER_MALFORMED_MSAAPPID);
    BIND_ENUM_CONSTANT(GDK_GAMEUSER_INCONSISTENT_MSAAPPID_AND_TITLEID);
    BIND_ENUM_CONSTANT(GDK_GAMEUSER_NO_MSAAPPID);

    BIND_ENUM_CONSTANT(GDK_GAMEPACKAGE_APP_NOT_PACKAGED);
    BIND_ENUM_CONSTANT(GDK_GAMEPACKAGE_NO_INSTALLED_LANGUAGES);
    BIND_ENUM_CONSTANT(GDK_GAMEPACKAGE_NO_STORE_ID);
    BIND_ENUM_CONSTANT(GDK_GAMEPACKAGE_INVALID_SELECTOR);
    BIND_ENUM_CONSTANT(GDK_GAMEPACKAGE_DOWNLOAD_REQUIRED);
    BIND_ENUM_CONSTANT(GDK_GAMEPACKAGE_NO_TAG_CHANGE);
    BIND_ENUM_CONSTANT(GDK_GAMEPACKAGE_DLC_NOT_SUPPORTED);
    BIND_ENUM_CONSTANT(GDK_GAMEPACKAGE_DUPLICATE_ID_VALUES);
    BIND_ENUM_CONSTANT(GDK_GAMEPACKAGE_NO_PACKAGE_IDENTIFIER);
    BIND_ENUM_CONSTANT(GDK_GAMEPACKAGE_CONFIG_NO_ROOT_NODE);
    BIND_ENUM_CONSTANT(GDK_GAMEPACKAGE_CONFIG_ZERO_VERSION);
    BIND_ENUM_CONSTANT(GDK_GAMEPACKAGE_CONFIG_NO_MSAAPPID_OR_TITLEID);
    BIND_ENUM_CONSTANT(GDK_GAMEPACKAGE_CONFIG_DEPRECATED_PC_ENTRIES);
    BIND_ENUM_CONSTANT(GDK_GAMEPACKAGE_CONFIG_SUM_REQUIRES_MSAAPPID);
    BIND_ENUM_CONSTANT(GDK_GAMEPACKAGE_CONFIG_NO_CODE_CLOUD_SAVES_REQUIRES_MSAAPPID);
    BIND_ENUM_CONSTANT(GDK_GAMEPACKAGE_CONFIG_MSAAPPID_OR_TITLEID_IS_DEFAULT);
    BIND_ENUM_CONSTANT(GDK_GAMEPACKAGE_CONFIG_INVALID_CONTROL_CHARACTERS);
    BIND_ENUM_CONSTANT(GDK_GAMEPACKAGE_CONFIG_PROTOCOL_REQUIRES_EXECUTABLE);
    BIND_ENUM_CONSTANT(GDK_GAMEPACKAGE_CONFIG_x64_EXECUTABLE_REQUIRED);

    BIND_ENUM_CONSTANT(GDK_GAMESTORE_LICENSE_ACTION_NOT_APPLICABLE_TO_PRODUCT);
    BIND_ENUM_CONSTANT(GDK_GAMESTORE_NETWORK_ERROR);
    BIND_ENUM_CONSTANT(GDK_GAMESTORE_SERVER_ERROR);
    BIND_ENUM_CONSTANT(GDK_GAMESTORE_INSUFFICIENT_QUANTITY);
    BIND_ENUM_CONSTANT(GDK_GAMESTORE_ALREADY_PURCHASED);
    BIND_ENUM_CONSTANT(GDK_GAMESTORE_LICENSE_ACTION_THROTTLED);

    BIND_ENUM_CONSTANT(GDK_GAMESTREAMING_NOT_INITIALIZED);
    BIND_ENUM_CONSTANT(GDK_GAMESTREAMING_CLIENT_NOT_CONNECTED);
    BIND_ENUM_CONSTANT(GDK_GAMESTREAMING_NO_DATA);
    BIND_ENUM_CONSTANT(GDK_GAMESTREAMING_NO_DATACENTER);
    BIND_ENUM_CONSTANT(GDK_GAMESTREAMING_NOT_STREAMING_CONTROLLER);
    BIND_ENUM_CONSTANT(GDK_GAMESTREAMING_NO_MATCH);
    BIND_ENUM_CONSTANT(GDK_GAMESTREAMING_TOO_MANY_CALLS);
    BIND_ENUM_CONSTANT(GDK_GAMESTREAMING_CUSTOM_RESOLUTION_NOT_SUPPORTED);
    BIND_ENUM_CONSTANT(GDK_GAMESTREAMING_CUSTOM_RESOLUTION_TOO_SMALL);
    BIND_ENUM_CONSTANT(GDK_GAMESTREAMING_CUSTOM_RESOLUTION_TOO_LARGE);
    BIND_ENUM_CONSTANT(GDK_GAMESTREAMING_CUSTOM_RESOLUTION_TOO_MANY_PIXELS);
    BIND_ENUM_CONSTANT(GDK_GAMESTREAMING_INVALID_CUSTOM_RESOLUTION);

    ClassDB::bind_method(D_METHOD("to_readable_code", "code"), &GDKError::to_readable_code);
    ADD_SIGNAL(MethodInfo("on_error", PropertyInfo(Variant::INT, "code"), PropertyInfo(Variant::STRING, "message")));
}

void GDKError::_notification(int p_what) {
    if (Engine::get_singleton()->is_editor_hint()) {
        return;
    }

    switch (p_what)
    {
    case NOTIFICATION_PREDELETE:
        {
            XErrorSetCallback(nullptr, nullptr);
        }
        break;
    }
}

bool ErrorCallback(HRESULT hr, const char* message, void* context) {
    GDKError* error = static_cast<GDKError*>(context);
    error->emit_signal("on_error", (int64_t)hr, String(message));
    return true;
}

GDKError::GDKError() {
    XErrorSetCallback(ErrorCallback, this);
}

String GDKError::to_readable_code(int64_t code) {
	return vformat("0x%08ux", (uint64_t)code);
}

void GDKError::SetErrorOptions(BitField<GDKXErrorOptions::Enum> optionsDebuggerPresent, BitField<GDKXErrorOptions::Enum> optionsDebuggerNotPresent) {
    XErrorOptions debuggerPresent = static_cast<XErrorOptions>((int64_t)optionsDebuggerPresent);
    XErrorOptions debuggerNotPresent = static_cast<XErrorOptions>((int64_t)optionsDebuggerNotPresent);

    XErrorSetOptions(debuggerPresent, debuggerNotPresent);
}

