#pragma once

#include <classes/ref_counted.hpp>
#include <windows.h>
#include <XGameErr.h>

namespace godot {
class GDKError: public RefCounted {
    GDCLASS(GDKError, RefCounted)

public:
    static constexpr inline int64_t GDK_OK = S_OK;
    static constexpr inline int64_t GDK_FALSE = S_FALSE;

    static constexpr inline int64_t GDK_DSTORAGE_BEGIN = E_DSTORAGE_BEGIN;
    static constexpr inline int64_t GDK_DSTORAGE_END = E_DSTORAGE_END;

    static constexpr inline int64_t GDK_GAMERUNTIME_NOT_INITIALIZED = E_GAMERUNTIME_NOT_INITIALIZED;
    static constexpr inline int64_t GDK_GAMERUNTIME_DLL_NOT_FOUND = E_GAMERUNTIME_DLL_NOT_FOUND;
    static constexpr inline int64_t GDK_GAMERUNTIME_VERSION_MISMATCH = E_GAMERUNTIME_VERSION_MISMATCH;
    static constexpr inline int64_t GDK_GAMERUNRIME_WINDOW_NOT_FOREGROUND = E_GAMERUNTIME_WINDOW_NOT_FOREGROUND;
    static constexpr inline int64_t GDK_GAMERUNTIME_SUSPENDED = E_GAMERUNTIME_SUSPENDED;
    static constexpr inline int64_t GDK_GAMERUNTIME_UNINITIALIZE_ACTIVEOBJECTS = E_GAMERUNTIME_UNINITIALIZE_ACTIVEOBJECTS;
    static constexpr inline int64_t GDK_GAMERUNTIME_MULTIPLAYER_NOT_CONFIGURED = E_GAMERUNTIME_MULTIPLAYER_NOT_CONFIGURED;
    static constexpr inline int64_t GDK_GAMERUNTIME_MISSING_DEPENDENCY = E_GAMERUNTIME_MISSING_DEPENDENCY;
    static constexpr inline int64_t GDK_GAMERUNTIME_SUSPENDED_ACTIVEOBJECTS = E_GAMERUNTIME_SUSPEND_ACTIVEOBJECTS;
    static constexpr inline int64_t GDK_GAMERUNTIME_OPTIONS_MISMATCH = E_GAMERUNTIME_OPTIONS_MISMATCH;
    static constexpr inline int64_t GDK_GAMERUNTIME_OPTIONS_NOT_SUPPORTED = E_GAMERUNTIME_OPTIONS_NOT_SUPPORTED;
    static constexpr inline int64_t GDK_GAMERUNTIME_GAMECONFIG_BAD_FORMAT = E_GAMERUNTIME_GAMECONFIG_BAD_FORMAT;
    static constexpr inline int64_t GDK_GAMERUNTIME_INVALID_HANDLE = E_GAMERUNTIME_INVALID_HANDLE;
    static constexpr inline int64_t GDK_GAMERUNTIME_SERVICE_NOT_AVAILABLE = E_GAMERUNTIME_SERVICE_NOT_AVAILABLE;
    
    static constexpr inline int64_t GDK_GAMEUSER_NO_AUTH_USER = E_GAMEUSER_NO_AUTH_USER;
    static constexpr inline int64_t GDK_GAMEUSER_USER_NOT_IN_SANDBOX = E_GAMEUSER_USER_NOT_IN_SANDBOX;
    static constexpr inline int64_t GDK_GAMEUSER_MAX_USERS_ADDED = E_GAMEUSER_MAX_USERS_ADDED;
    static constexpr inline int64_t GDK_GAMEUSER_SIGNED_OUT = E_GAMEUSER_SIGNED_OUT;
    static constexpr inline int64_t GDK_GAMEUSER_RESOLVE_USER_ISSUE_REQUIRED = E_GAMEUSER_RESOLVE_USER_ISSUE_REQUIRED;
    static constexpr inline int64_t GDK_GAMEUSER_DEFERRAL_NOT_AVAILABLE = E_GAMEUSER_DEFERRAL_NOT_AVAILABLE;
    static constexpr inline int64_t GDK_GAMEUSER_USER_NOT_FOUND = E_GAMEUSER_USER_NOT_FOUND;
    static constexpr inline int64_t GDK_GAMEUSER_NO_TOKEN_REQUIRED = E_GAMEUSER_NO_TOKEN_REQUIRED;
    static constexpr inline int64_t GDK_GAMEUSER_NO_DEFAULT_USER = E_GAMEUSER_NO_DEFAULT_USER;
    static constexpr inline int64_t GDK_GAMEUSER_FAILED_TO_RESOLVE = E_GAMEUSER_FAILED_TO_RESOLVE;
    static constexpr inline int64_t GDK_GAMEUSER_NO_TITLE_ID = E_GAMEUSER_NO_TITLE_ID;
    static constexpr inline int64_t GDK_GAMEUSER_UNKNOWN_GAME_IDENTITY = E_GAMEUSER_UNKNOWN_GAME_IDENTITY;
    static constexpr inline int64_t GDK_GAMEUSER_NO_PACKAGE_IDENTITY = E_GAMEUSER_NO_PACKAGE_IDENTITY;
    static constexpr inline int64_t GDK_GAMEUSER_FAILED_TO_GET_TOKEN = E_GAMEUSER_FAILED_TO_GET_TOKEN;
    static constexpr inline int64_t GDK_GAMEUSER_INVALID_APP_CONFIGURATION = E_GAMEUSER_INVALID_APP_CONFIGURATION;
    static constexpr inline int64_t GDK_GAMEUSER_MALFORMED_MSAAPPID = E_GAMEUSER_MALFORMED_MSAAPPID;
    static constexpr inline int64_t GDK_GAMEUSER_INCONSISTENT_MSAAPPID_AND_TITLEID = E_GAMEUSER_INCONSISTENT_MSAAPPID_AND_TITLEID;
    static constexpr inline int64_t GDK_GAMEUSER_NO_MSAAPPID = E_GAMEUSER_NO_MSAAPPID;
    
    static constexpr inline int64_t GDK_GAMEPACKAGE_APP_NOT_PACKAGED = E_GAMEPACKAGE_APP_NOT_PACKAGED;
    static constexpr inline int64_t GDK_GAMEPACKAGE_NO_INSTALLED_LANGUAGES = E_GAMEPACKAGE_NO_INSTALLED_LANGUAGES;
    static constexpr inline int64_t GDK_GAMEPACKAGE_NO_STORE_ID = E_GAMEPACKAGE_NO_STORE_ID;
    static constexpr inline int64_t GDK_GAMEPACKAGE_INVALID_SELECTOR = E_GAMEPACKAGE_INVALID_SELECTOR;
    static constexpr inline int64_t GDK_GAMEPACKAGE_DOWNLOAD_REQUIRED = E_GAMEPACKAGE_DOWNLOAD_REQUIRED;
    static constexpr inline int64_t GDK_GAMEPACKAGE_NO_TAG_CHANGE = E_GAMEPACKAGE_NO_TAG_CHANGE;
    static constexpr inline int64_t GDK_GAMEPACKAGE_DLC_NOT_SUPPORTED = E_GAMEPACKAGE_DLC_NOT_SUPPORTED;
    static constexpr inline int64_t GDK_GAMEPACKAGE_DUPLICATE_ID_VALUES = E_GAMEPACKAGE_DUPLICATE_ID_VALUES;
    static constexpr inline int64_t GDK_GAMEPACKAGE_NO_PACKAGE_IDENTIFIER = E_GAMEPACKAGE_NO_PACKAGE_IDENTIFIER;
    static constexpr inline int64_t GDK_GAMEPACKAGE_CONFIG_NO_ROOT_NODE = E_GAMEPACKAGE_CONFIG_NO_ROOT_NODE;
    static constexpr inline int64_t GDK_GAMEPACKAGE_CONFIG_ZERO_VERSION = E_GAMEPACKAGE_CONFIG_ZERO_VERSION;
    static constexpr inline int64_t GDK_GAMEPACKAGE_CONFIG_NO_MSAAPPID_OR_TITLEID = E_GAMEPACKAGE_CONFIG_NO_MSAAPPID_OR_TITLEID;
    static constexpr inline int64_t GDK_GAMEPACKAGE_CONFIG_DEPRECATED_PC_ENTRIES = E_GAMEPACKAGE_CONFIG_DEPRECATED_PC_ENTRIES;
    static constexpr inline int64_t GDK_GAMEPACKAGE_CONFIG_SUM_REQUIRES_MSAAPPID = E_GAMEPACKAGE_CONFIG_SUM_REQUIRES_MSAAPPID;
    static constexpr inline int64_t GDK_GAMEPACKAGE_CONFIG_NO_CODE_CLOUD_SAVES_REQUIRES_MSAAPPID = E_GAMEPACKAGE_CONFIG_NO_CODE_CLOUD_SAVES_REQUIRES_MSAAPPID;
    static constexpr inline int64_t GDK_GAMEPACKAGE_CONFIG_MSAAPPID_OR_TITLEID_IS_DEFAULT = E_GAMEPACKAGE_CONFIG_MSAAPPID_OR_TITLEID_IS_DEFAULT;
    static constexpr inline int64_t GDK_GAMEPACKAGE_CONFIG_INVALID_CONTROL_CHARACTERS = E_GAMEPACKAGE_CONFIG_INVALID_CONTROL_CHARACTERS;
    static constexpr inline int64_t GDK_GAMEPACKAGE_CONFIG_PROTOCOL_REQUIRES_EXECUTABLE = E_GAMEPACKAGE_CONFIG_PROTOCOL_REQUIRES_EXECUTABLE;
    static constexpr inline int64_t GDK_GAMEPACKAGE_CONFIG_x64_EXECUTABLE_REQUIRED = E_GAMEPACKAGE_CONFIG_x64_EXECUTABLE_REQUIRED;

    static constexpr inline int64_t GDK_GAMESTORE_LICENSE_ACTION_NOT_APPLICABLE_TO_PRODUCT = E_GAMESTORE_LICENSE_ACTION_NOT_APPLICABLE_TO_PRODUCT;
    static constexpr inline int64_t GDK_GAMESTORE_NETWORK_ERROR = E_GAMESTORE_NETWORK_ERROR;
    static constexpr inline int64_t GDK_GAMESTORE_SERVER_ERROR = E_GAMESTORE_SERVER_ERROR;
    static constexpr inline int64_t GDK_GAMESTORE_INSUFFICIENT_QUANTITY = E_GAMESTORE_INSUFFICIENT_QUANTITY;
    static constexpr inline int64_t GDK_GAMESTORE_ALREADY_PURCHASED = E_GAMESTORE_ALREADY_PURCHASED;
    static constexpr inline int64_t GDK_GAMESTORE_LICENSE_ACTION_THROTTLED = E_GAMESTORE_LICENSE_ACTION_THROTTLED;

    static constexpr inline int64_t GDK_GAMESTREAMING_NOT_INITIALIZED = E_GAMESTREAMING_NOT_INITIALIZED;
    static constexpr inline int64_t GDK_GAMESTREAMING_CLIENT_NOT_CONNECTED = E_GAMESTREAMING_CLIENT_NOT_CONNECTED;
    static constexpr inline int64_t GDK_GAMESTREAMING_NO_DATA = E_GAMESTREAMING_NO_DATA;
    static constexpr inline int64_t GDK_GAMESTREAMING_NO_DATACENTER = E_GAMESTREAMING_NO_DATACENTER;
    static constexpr inline int64_t GDK_GAMESTREAMING_NOT_STREAMING_CONTROLLER = E_GAMESTREAMING_NOT_STREAMING_CONTROLLER;
    static constexpr inline int64_t GDK_GAMESTREAMING_NO_MATCH = E_GAMESTREAMING_NO_MATCH;
    static constexpr inline int64_t GDK_GAMESTREAMING_TOO_MANY_CALLS = E_GAMESTREAMING_TOO_MANY_CALLS;
    static constexpr inline int64_t GDK_GAMESTREAMING_CUSTOM_RESOLUTION_NOT_SUPPORTED = E_GAMESTREAMING_CUSTOM_RESOLUTION_NOT_SUPPORTED;
    static constexpr inline int64_t GDK_GAMESTREAMING_CUSTOM_RESOLUTION_TOO_SMALL = E_GAMESTREAMING_CUSTOM_RESOLUTION_TOO_SMALL;
    static constexpr inline int64_t GDK_GAMESTREAMING_CUSTOM_RESOLUTION_TOO_LARGE = E_GAMESTREAMING_CUSTOM_RESOLUTION_TOO_LARGE;
    static constexpr inline int64_t GDK_GAMESTREAMING_CUSTOM_RESOLUTION_TOO_MANY_PIXELS = E_GAMESTREAMING_CUSTOM_RESOLUTION_TOO_MANY_PIXELS;
    static constexpr inline int64_t GDK_GAMESTREAMING_INVALID_CUSTOM_RESOLUTION = E_GAMESTREAMING_INVALID_CUSTOM_RESOLUTION;

protected:
    static void _bind_methods();
    static String to_readable_code(int64_t code);
};

}